name: Daily ROI Processor

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:     # Allows manual triggering

jobs:
  process-roi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Changed to PHP 8.1
        extensions: mysqli
        tools: composer
        
    - name: Run ROI Script
      run: |
        php cron/daily_roi_cron.php
      env:
        DB_HOST: "localhost"  # Hardcoded value
        DB_USER: "root"       # Hardcoded value
        DB_PASS: ""       # Hardcoded value
        DB_NAME: "u255754182_eightcap"           # Hardcoded value
        APP_ENV: production
        
    - name: Archive error logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cron-logs
        path: |
          cron_errors.log
          cron.log