name: Daily ROI Processor
on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:     # Allows manual triggering

jobs:
  process-roi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli
        tools: composer
        
    - name: Run ROI Script
      run: |
        cd roiCronJob && php roi_income_release.php
      env:
        DB_HOST: "localhost"
        DB_USER: "root"
        DB_PASS: ""
        DB_NAME: "u255754182_eightcap"
        APP_ENV: production
        
    - name: Archive error logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cron-logs
        path: |
          roiCronJob/cron_errors.log
          roiCronJob/cron.log
